name: ""
description: ""

url: "http://ycpcs.github.io/cs482-spring2016"

markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge